### ISSUE TITLE
"Generate" toggle is missing on enabled entity forms and paths don't get generated

### ISSUE THREAD

**Issue by banoodle** [kanopi/saplings-content-types#14]
## What I saw

![Screenshot 2024-03-25 at 2 39 44 PM](https://github.com/kanopi/saplings-content-types/assets/7685811/1a67b7f6-83b1-4f34-b1d6-86a544007746)

## What I expected to see

![Screenshot 2024-03-25 at 2 39 55 PM](https://github.com/kanopi/saplings-content-types/assets/7685811/cadb5daf-0509-4de6-9f3f-94f5a8925358)

**Comment by thejimbirch** [comment]
Merged #15
