### ISSUE TITLE
Unable to update the display of fields for page content type

### ISSUE THREAD

**Issue by kmurphychi247** [kanopi/saplings-content-types#3]
There is an odd issue happening with the page content type.  We can not set the display of the teaser to a pattern.  In addition, it is also impossible to update the display of any of the fields.  

/admin/structure/types/manage/sa_page/display
note that several of the fields are set to use the bootstrap layout classes display here.  Attempt to update them and save and they immediately revert back to the bootstrap classes layout display.

**Comment by thejimbirch** [comment]
- Navigate to /admin/structure/types/manage/sa_page/display
- In the Disabled section, changes `Robots meta tag` and `SEO Page Title` to another field format like plain text
- Save
- Verify the field format did not save.

**Comment by thejimbirch** [comment]
- Navigate to /admin/structure/types/manage/sa_page/display
- Move the `Robots meta tag` and `SEO Page Title` from the disabled section and see they change to Plain text
- Save
- Verify they stayed Plain text

**Comment by thejimbirch** [comment]
- Navigate to: `/admin/structure/types/manage/sa_page/display/teaser`
- Verify the contrib field formatter module throws a fatal error:

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 12288 bytes) in /code/web/modules/contrib/field_formatter/src/Plugin/Field/FieldFormatter/FieldWrapperBase.php on line 73 Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 12288 bytes) in /code/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php on line 422 Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /code/web/core/includes/errors.inc on line 29 ```

**Comment by thejimbirch** [comment]
Testing can be done on this multdev https://error-drupal-starter-demo.pantheonsite.io/

**Comment by thejimbirch** [comment]
Known issue on https://www.drupal.org/project/ui_patterns_field_formatters

Issue with a patch that fixes it has been merged into dev.
https://www.drupal.org/project/field_formatter/issues/3333885

`fin composer require 'drupal/field_formatter:3.x-dev@dev'` fixes the issue.

I am going to see in which recipe we require this module and upgrade it to dev.

**Comment by thejimbirch** [comment]
Added a new release to saplings-theme that hopefully fixes this.

https://github.com/kanopi/saplings-theme/releases/tag/0.0.10

**Comment by kmurphychi247** [comment]
Tested and works well.  Thank you!
